apiVersion: v1
kind: Service
metadata:
  name: node-service

spec:
  type: ClusterIP

  selector:
    app: node

  ports:
    - port: {{ .Values.node.port }}
      targetPort: {{ .Values.node.port }}
